backend/blueprints/auth.py
""" Defines routes for user authentication """

from flask import Blueprint, render_template, request, redirect, url_for, session, jsonify, Response, current_app
import bcrypt
from ..models import *
from typing import Union

auth_blueprint: Blueprint = Blueprint('auth', __name__, 
                                      template_folder='../../templates', 
                                      static_folder='../../static')

#db: SQLAlchemy = current_app.db

@auth_blueprint.route('/')
def index() -> Response:
    """
    Home page

    Currently redirects to 
        -login page if not logged in
        -user home page if logged in

    :returns: Redirecting Response
    """
    if 'username' in session :
        return redirect(url_for('auth.home'))
    return redirect(url_for('auth.login'))

@auth_blueprint.route('/login', methods=['GET', 'POST'])
def login() -> Union[str , Response]:
    """
    GET:
        render the login page
    :returns: template-rendering str

    POST:
        submit a login request
    :returns: Response object specifing if successful login or not
    """
    if request.method == 'GET':
        # Render the login form template if not logged in
        if 'username' in session :
            return redirect(url_for('auth.home'))
        return render_template('login.html')
    elif request.method == 'POST':
        email: str = request.form.get('email')
        password: str = request.form.get('password')

        # get user from database 
        user: User = current_app.db.session.get(User, email)

        # Check if user's password is correct
        if user: # also encry on the frontend
            stored_hashed_password: str = user.password
            if bcrypt.checkpw(password.encode('utf-8'),
                            stored_hashed_password.encode('utf-8')):
                session['email'] = user.email
                session['username'] = user.email
                return jsonify(status='success'), 200
            else:
                return jsonify(status='error',  message='Incorrect email or password'), 401
        else:
            return jsonify(status='error', message='Username not found'), 401


@auth_blueprint.route('/profile') 
def profile() -> str | Response:
    """ 
    Gets events onwned by user (see get_user_events method) and returns to JS, which then executes
    get_event to get the information from each event to display.
    """
    if 'username' not in session:
        return redirect(url_for('auth.index'))
    username: str = session['username']
    events = None
    return render_template('profile.html', username=username, events=events)

@auth_blueprint.route('/home')
def home() -> Response:
    """
    Gets groups and events owned by user (use get_user_events and get_user_groups) 
    and return to JS, which then executes
    """
    if 'username' not in session:
        return redirect(url_for('auth.index'))
    email: str = session.get('email')
    
    # Use the SQLAlchemy query attribute for Membership

    user_memberships = current_app.db.session.scalars(current_app.db.select(Membership).filter_by(user_email=email))
    if user_memberships:
        user_groups = [membership.group for membership in user_memberships]
        # initiate list of events to render in home.html
        user_events=[]
        # Loop through groups, and get each event to display in the home page
        for group in user_groups:
            group_id = group.id
            user_events_result = current_app.db.session.scalars(current_app.db.select(Event).filter_by(group_id = group_id))

            for event in user_events_result:
                # Only append valid events, no null events
                if event:
                    user_events.append(event)
        # Render home.html with username from session, groups and events the user participates in.
        return render_template('home.html', username=session.get('username'), user_groups=user_groups, user_events=user_events)
    else: 
        return render_template('home.html', username=session['username'])
    
@auth_blueprint.route('/signup')
def signup() -> str | Response :
    """
    Renders the signup.html page
        or redirects to user home if logged in
    """
    if 'username' in session :
        return redirect(url_for('auth.home'))
    return render_template('signup.html')

@auth_blueprint.route('/logout', methods=['POST'])
def logout() -> Response :
    """
    Logs user out by removing data from session
        and redirecting to the launch page
    """
    if 'username' in session:
        session.pop('username', None)
        session.pop('email', None)
    return redirect(url_for('auth.index'))

@auth_blueprint.route('/signup-request',  methods=['POST'])
def signup_request() -> Response:
    """
    Processes a signup request from the signup page

    :return: Response object with status='success' if 
        successful signup or status='error' if failed
    """
    email: str = request.form.get('email')
    username: str = request.form.get('username')
    password: str = request.form.get('password')

    # check if user already exists
    if current_app.db.session.get(User, email) :
        return jsonify(status='error',  
                    message='An account is already associated with the provided email'), 412

    # hashed_password  # make sure also encry at the frontend
    hashed_password: bytes = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())

    # create a User object
    new_user: User = User(email, username, hashed_password)

    # add new_user to db
    current_app.db.session.add(new_user)
    current_app.db.session.commit()

    # notify success
    return jsonify(status='success'), 201


@auth_blueprint.route('/get-notifications',  methods=['GET'])
def get_user_notifications() -> Response :
    """ 
    Returns all the notifications associated with the current user.
    Currently, just returns the group invites
    """
    # get the user's email from session
    user_email: str | None = session.get('email')

    # check if user_email exists
    if not user_email :
        return jsonify(status='failure'), 500
    
    # get and validate user
    user: User | None = current_app.db.session.get(User, user_email)

    if not user :
        return jsonify(status='failure'), 500

    # get users group invites
    inviting_groups: List[Group] = user.get_group_invites()
    print(inviting_groups)
    # return
    return jsonify([{'id': group.id, 'name': group.name} for group in inviting_groups]), 200

backend/blueprints/groups.py
""" Defines group related routes """

from flask import Blueprint, render_template, request, redirect, url_for, session, jsonify, Response, current_app
from ..models import *
from flask_mail import Mail, Message
from ..blueprints.events import create_event, add_participant_to_event
from sqlalchemy import select

from sqlalchemy.orm import selectinload

groups_blueprint: Blueprint = Blueprint('groups', __name__, 
                                        template_folder='../../templates', 
                                        static_folder='../../static')




@groups_blueprint.route('/create_group', methods=['GET', 'POST'])
def create_group() -> Response:
    """ 
    This method will be made for creating groups. It'll allow for someone to make a group such as 
    CS506Fall23. It will get information such as group name and description. An SQL query will be
    executed to save the group to the database, and then once done it will redirect to home page.
    """
    # Step1: get information from the user such as event name and description.
    group_name: str = request.args.get('groupName')
    group_description: str = request.args.get('groupDescription')
    
    
    # Step2: create group and make the user a member
    new_group: Group = Group(group_name, group_description)
    email: str = session.get('email')
    new_membership: Membership = Membership(email, None, 'owner')
    new_group.memberships.append(new_membership)

    current_app.db.session.add_all([new_group, new_membership])
    current_app.db.session.commit()

    # Step3: redirect to home page. 
    return redirect(url_for('auth.home'))

def is_group_admin(group_id: int, user_id: int) -> bool:
    """ 
    determines if the user of user_id an admin of 
        the group of group_id #TODO
    """
    # Connect to the database
    db = None
    cursor = db.cursor()

    try:
        # Query to check if the user is the admin of the group
        query = "SELECT admin_id FROM groups WHERE group_id = %s"
        cursor.execute(query, (group_id,))
        admin_id = cursor.fetchone()

        # Check if the user_id matches the admin_id
        if admin_id and user_id == admin_id[0]:
            return True  # The user is the admin of the group
        else:
            return False  # The user is not the admin of the group

    except Exception as e:
        # Handle any potential errors, such as database connection issues
        print(f"Error checking group admin: {str(e)}")
        return False  # Return False to indicate that an error occurred

    finally:
        cursor.close()
        db.close()

def get_group_members(group_id: int) -> List[int] :
    """get the group members correlated with group_id"""
    # Connect to the database
    db = None
    cursor = db.cursor()

    try:
        # Query to retrieve a list of member IDs for the specified group
        query = "SELECT user_id FROM group_members WHERE group_id = %s"
        cursor.execute(query, (group_id,))
        member_ids = [result[0] for result in cursor.fetchall()]

        return member_ids  # Return a list of member IDs

    except Exception as e:
        # Handle any potential errors, such as database connection issues
        print(f"Error retrieving group members: {str(e)}")
        return []  # Return an empty list to indicate that an error occurred

    finally:
        cursor.close()
        db.close()

@groups_blueprint.route('/get-group-id', methods=['GET'])
def get_group_id() -> Response :
    """ Retreives a group_id given a specified group name """
    # get the group name from the request parameters
    group_name = request.args.get('group_name')

    # query the database to find group_id for specified group_name
    db = None
    cursor = db.cursor
    cursor.execute("SELECT id from 'group' WHERE name = %s", (group_name,))
    result = cursor.fetchone()

    if result: 
        group_id = result[0]
        return jsonify({'group_id': group_id}) # success: return group_id
    else: 
        return jsonify({'error': 'Group not found'}), 404 # failure: return error response

@groups_blueprint.route('/send-invitations/<int:group_id>', methods=['POST'])
def send_invitations(group_id: int) -> Response :
   """ Sends group invitations to users via email using Flask-Mail API """
   # get Mail instance
   mail = Mail(current_app)

   # Get JSON data (list of emails), sent from the frontend
   data = request.get_json()

   # Extract email addresses
   emails = data.get('emails', [])

   for email in emails :
       # check if user exists
       if not current_app.db.session.get(User, email) :
           continue
       # check if the user is already a member of the group
       existing_membership = current_app.db.session.get(Membership, (email, group_id))

       # if user is not already a member, add them as an invitee
       if not existing_membership:
           new_membership = Membership(user_email=email, group_id=group_id, role='invitee')

           # add the new invitee to the session and commit
           current_app.db.session.add(new_membership)
           current_app.db.session.commit()

   # TODO: Process the emails, e.g., send invitation emails, save to the database, etc.
   # For now, let's just print them for demonstration purposes
   #print(emails)

   # sending invitation email functionality through Flask-Mail API

   # for each email in email list, send an invitation email 
   """
   for email in emails:
       message = Message(subject='You have been invited to a group!', recipients=[email])
       message.body = f'You are invited to a group with ID {group_id}. Please log into the Scheduler App to accept your invitation!'
       try:
           mail.send(message)
       except Exception as e:
           print(f'Error sending invitation email to {email}: {str(e)}')
        """
           

   return jsonify(status='success', message='Invitations sent successfully!'), 201

#@events_blueprint.route('/group/<int:group_id>/create-event', methods=['POST'])
def create_group_event(group_id: int) -> Response:
    """ Create a group level event """

    # Authenticate the user and check if they are the group admin
    current_user_id = session.get('user_id')
    if not is_group_admin(group_id, current_user_id):
        return jsonify({"status": "error", "message": "You do not have permission to create group events."}), 403

    # Get event details from the request
    data = request.get_json()
    event_name = data.get('event_name')
    event_description = data.get('event_description')
    start_date = data.get('start_date')
    end_date = data.get('end_date')
    recurring = data.get('recurring')  # TODO: false type, look at the db and start_day and end_date

    # Retrieve the list of group members
    group_members = get_group_members(group_id)

    if not group_members:
        return jsonify({"status": "error", "message": "No group members found."}), 404

    # Create the event in the database
    event_id = create_event(event_name, event_description, start_date, end_date, recurring)

    if event_id:
        # Add all group members as event participants
        for member_id in group_members:
            add_participant_to_event(event_id, member_id)

        return jsonify({"status": "success", "message": "Group event created successfully."}), 201
    else:
        return jsonify({"status": "error", "message": "Event creation failed. Please check your input."}), 500
@groups_blueprint.route('/join_group/', methods = ['GET', 'POST'])
def join_group()-> Response:
    """ This method is being written to handle the functionality of joining a group from a members side, by inputting
        a valid group ID. The user will still need to be allowed in by the owner/admins of the group, and we assume the
        user has been sent the valid group ID, and is a valid member.
    """
    user_email = session.get('email')
    # step 1: check that group_id is valid and exists, and that user is not member of the group else show error message
    group_id = request.form.get('groupCode')
    valid_group =  current_app.db.session.get(Group, group_id)
    membership = current_app.db.session.query(Membership).filter_by(group_id=group_id, user_email=user_email).first()
    print("group_id:", group_id)
    print("membership:", membership)
    if((not valid_group) or membership):   
        return jsonify(status='error',  message='Group ID incorrect or group does not exist'), 401
    # step2: if valid, send notification to group admin where they can accept or deny the request
    else:
        # Add user to database with role requester
        new_membership = Membership(user_email=user_email, group_id=group_id, role='requester')
        # Get Owner of groups ID
        # membership = current_app.db.session.query(Membership).filter_by(group_id=group_id).first()
        # owner = membership.user_email
        # # Send message to owner of group with requester ID
        # group_name = valid_group.name
        # message = Message(subject='A new User wants to join your group!', recipients=[owner])
        # message.body = f'User {user_email} wants to join group {group_name} with ID {group_id}. Please log into the Scheduler App to review this request!'
        current_app.db.session.add(new_membership)
        current_app.db.session.commit()
        # try:
        #     mail.send(message)
        # except Exception as e:
        #     print(f'Error sending request, try again please')
        return redirect(url_for('auth.home'))
    # step 3: if step 1 and 2 were completed regularly, close modal, reload home page.

@groups_blueprint.route('/group/<int:group_id>') 
def group_page(group_id):
    """ This method is used to redirect from the home page to a group page, when the user clicks
        on a group in their home page. The user must be a part of the group, whether a member or admin,

templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Ten Star User Home Page</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/home.css') }}" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{{ url_for('static', filename='scripts/home.js') }}"></script>
</head>

<body>
    <div class="wrapper">
        <!-- Nav Bar -->
        <nav class="navbar">
            <!-- on the left side there will be an iamge-->
            <div class="navbar-left">
                <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Ten Star Logo" />
            </div>
            <!-- on the right side there will be buttons-->
            <div class="navbar-right">
                <!-- welcome button -->
                <button id="welcomeButton" style="display: block">
                    Welcome, {{ username }}!
                </button>
                <form action="{{ url_for('auth.logout') }}" method="post" id="logoutForm" style="display: none">
                    <button type="submit" class="btn btn-danger">Logout</button>
                </form>
                <!-- profile button -->
                <button id="editProfile" class="btn btn-danger" style="display: block">
                    Profile
                </button>
                <!-- create event button -->
                <button id="createGroupButton" class="btn btn-danger" style="display: block">
                    Create Groups
                </button>
                <button id="joinGroupButton" class="btn btn-danger" style="display: block">
                    Join Group
                </button>

                <!-- notification button -->
                <div class="notification-container">
                    <button class="notification-btn">Notifications</button>
                    <!-- Notification dropdown -->
                    <div class="notification-dropdown" style="display: none">
                        <!-- Sample notification item -->
                    </div>
                </div>
            </div>
        </nav>
        <div class="container">
            <!-- Switch button to toggle between Groups and Events -->
            <div class="switch-selector">
                <button id="showGroups" class="active selected">Groups</button>
                <button id="showEvents">Events</button>
            </div>
            <!-- Box to display the groups -->
            {% for group in user_groups %}
            {% if group.memberships[0].role != 'invitee' and group.memberships[0].role != 'requester' %}
            <div class="group {% if group.memberships[0].role == 'owner' %}admin-group{% else %}participant-group{% endif %}" data-group-url="{{ url_for('groups.group_page', group_id=group.id) }}" data-group-id="{{ group.id }}">
                <h2>{{ group.name }}</h2>
                <p>Members: {{ group.memberships | length }}</p>
                <p>group ID: {{ group.id }}</p>
            </div>
            {% endif %}
            {% endfor %}
            <!-- Box to display the events -->
            {% if user_events %}
                <ul>
                    <div class="event-box">
                        {% for event in user_events %}
                            <div class="event group-event">
                                <h3 class="event-name">{{ event.name }}</h3>
                                <div class="event-members">
                                    <p>{{ event.description }}</p>
                                </div>
                                <div class="event-dates">
                                    <p>Start Date: {{ event.start_date }}</p>
                                    <p>End Date: {{ event.end_date }}</p>
                                    <p>{{event.reg_start_day}}</p>
                                </div>
                                <h3 class="event-name">Group Name: {{ event.group.name }}</h3>
                            </div>
                        {% endfor %}
                    </div>
                </ul>
            {% else %}
                <p>No events</p>
            {% endif %}
        </div>
    </div>
    <!-- Create Group Modal -->
    <div id="createGroupModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h2>Create Group</h2>
            <form id="createGroupForm" action="{{ url_for('groups.create_group') }}">
                <div class="form-group">
                    <label for="groupName">Group Name:</label>
                    <input type="text" id="groupName" name="groupName" required />
                </div>
                <div class="form-group">
                    <label for="groupDescription">Group Description:</label>
                    <textarea id="groupDescription" name="groupDescription" required></textarea>
                </div>
                <button type="submit" class="btn btn-danger btn-create-group" >Create Group</button>
            </form>
        </div>
    </div>
    <div id="joinGroupModal" class="modal">
        <div class="modal-content">
            <span class="jclose">&times;</span>
            <h2>Join Group Via Code</h2>
            <form id="joinGroupForm" action="{{ url_for('groups.join_group') }}", method="POST">
                <div class="form-group">
                    <input type="text" id="groupCode" name="groupCode" required />
                </div>
                <button id = "joinGroup" type="submit" class="btn btn-danger btn-join-group" >Join Group</button>
            </form>
        </div>
    </div>
</body>

</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Login Page</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='styles/styles.css') }}">
        <!-- Including jQuery from a CDN -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    </head>
    <body>
        <div class="container">
            <form id="loginForm">
                <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Ten Star Logo">
                <div>
                    <label for="email">Email:</label>
                    <input type="email" name="email" required placeholder="Email">
                </div>
                <div>
                    <label for="password">Password:</label>
                    <input type="password" name="password" required placeholder="Password">
                </div>
                <div>
                    <button type="submit">Login</button>
                </div>
            </form>
            <div id="error-message" style="color: red;"></div>
            <p>New to tenstars ? <a href="./signup">Sign Up</a></p>
        </div>
        <script src="{{ url_for('static', filename='scripts/login.js') }}"></script>
    </body>
</html>

templates/manual_create_team.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Ten Star User Home Page</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/manual_create_team.css') }}" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{{ url_for('static', filename='scripts/manual_create_team.js') }}"></script>
    <!-- Flatpickr CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">


    <!-- Flatpickr JS -->
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
</head>

<body>
    <div class="wrapper">
        <!-- Nav Bar -->
        <nav class="navbar">
            <!-- on the left side there will be an iamge-->
            <div class="navbar-left">
                <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Ten Star Logo" />
            </div>
            <!-- on the right side there will be buttons-->
            <div class="navbar-right">
                <button class="btn btn-danger" style="display: block" onclick="window.location.href='/group/{{ group_id }}';">
                    Back
                </button>
            </div>
        </nav>

        <div class="container">
            <!-- Other Sections -->
            <!-- Expandable Member Selection Section -->
            <div class="section" style="position: relative;">
                <span class="section-text" onclick="toggleVisibility('memberSelection')">Create Team</span>
                <!-- The rest of your content -->
                <div id="memberSelection" style="display: none;">
                    <label for="teamName" class="input-label">Team Name</label>
                    <input type="text" id="teamName" placeholder="E.g., Alpha Team" class="input-text">

                    <label for="teamDescription" class="input-label">Team Description</label>
                    <textarea id="teamDescription" placeholder="Describe the team's purpose and goals" class="textarea-description"></textarea>
                    <div class="search-bar">
                        <input type="text" id="searchPeople" placeholder="Search people..." onkeyup="searchPeople()">
                        <button id="checkAll">Check All</button>
                    </div>
                    <div class="team-members" id="peopleContainer">
                        {% for person in people %}
                        <label class="member" for="chk{{ person['username'] }}">
                            <input type="checkbox" id="chk{{ person['username'] }}" value="{{ person['username'] }}" data-email="{{ person['email'] }}">
                            <span class="checkmark"></span>
                            {{ person['username'] }}
                        </label>
                        {% endfor %}
                    </div>
                    <!-- Confirm button -->
                    <button onclick="confirmParticipants()" id="confirmButton">Confirm</button>
                </div>
                <!-- Container for showing selected participants -->
                <div id="selectedParticipants" style="display: none;">
                    <!-- Selected participants will be listed here -->
                </div>
            </div>
            <div id="finalButton">
                <button onclick="createTeam()">Create Teams</button>
            </div>

        </div>

    </div>


</body>

</html>

templates/profile.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>User Weekly Schedule</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/profile.css') }}" />
</head>

<body>
    <!-- Nav Bar -->
    <nav class="navbar">
        <!-- on the left side there will be an iamge-->
        <div class="navbar-left">
            <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Ten Star Logo" />
        </div>
        <!-- on the right side there will be buttons-->
        <div class="navbar-right">
            <!-- welcome button -->
            <button id="welcomeButton" style="display: block">
                Welcome, {{ username }}!
            </button>
            <form action="{{ url_for('auth.logout') }}" method="post" id="logoutForm" style="display: none">
                <button type="submit" class="btn btn-danger">Logout</button>
            </form>
            <button class="btn btn-danger" style="display: block" onclick="window.location.href='/home';">
                Back
            </button>
        </div>
    </nav>


    <!-- The Container -->
    <div class="container">
        <h1>User Weekly Schedule</h1>
        <!-- Day Boxes -->
        <div id="schedule-container">
            <div class="day" id="monday">Monday</div>
            <div class="day" id="tuesday">Tuesday</div>
            <div class="day" id="wednesday">Wednesday</div>
            <div class="day" id="thursday">Thursday</div>
            <div class="day" id="friday">Friday</div>
            <div class="day" id="saturday">Saturday</div>
            <div class="day" id="sunday">Sunday</div>
        </div>
        <div id="avail-blocks">
            <!-- Dynamically added avail blocks can go here -->
        </div>

        <div class="button-container">
            <!-- Button to open the modal to add a new avail -->
            <button id="create-avail-btn" class="btn btn-primary">Create Availability</button>
            <!-- Button to save schedule and send avail blocks to backend -->
            <button id="saveScheduleButton" class="btn btn-success">Save Schedule</button>
        </div>
    </div>

    <!-- The Modal -->
    <div id="avail-modal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <form id="avail-form">
                <label for="avail-start" class="start-time-label">Start Time:</label>
                <input type="time" id="avail-start" name="avail-start" required />

                <label for="avail-end" class="end-time-label">End Time:</label>
                <input type="time" id="avail-end" name="avail-end" required />

                <input type="submit" value="Create Availability Block" />
            </form>
        </div>
    </div>
    <script src="{{ url_for('static', filename='scripts/profile.js') }}"></script>
</body>
</html>

templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head> <!-- indention not consistent -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ten Star Sign Up</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/styles.css') }}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
    <div class="container">
        <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Ten Star Logo">
        <form id="signupForm"> <!-- add required keyword to forms; maybe use classes instead of other attributes-->
            <label for="username">Name</label>
            <input type="username" id="username" name="username" placeholder="Name">

            <label for="email">Email</label>
            <input type="email" id="email" name="email" placeholder="Email">

            <label for="password">Password</label>
            <input type="password" id="password" name="password" placeholder="Password">

            <button>SIGN UP</button>
        </form>
            <p>ALREADY HAS AN ACCOUNT? <a href="login">LOG IN</a></p>
        <p id="error-message" style="color:red;"></p>
    </div>
    <script src="{{ url_for('static', filename='scripts/signup.js') }}"></script>
</body>
</html>